local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {

	s("!t", {
		t({
			'#import "@preview/lovelace:0.3.0": no-number, pseudocode-list, with-line-label',
			"",
			"// update these headers",
			'#let sid = "550486709"',
			'#let type = "Tutorial" // Switch between Tutorial / Assignment / Lecture',
			'#let number = "1"',
			"",
			"// page setup",
			"#set page(",
			'  paper: "a4",',
			"  margin: 2.5cm,",
			"  header: [",
			"    #grid(",
			"      columns: (1fr, 1fr, 1fr),",
			'      align(left)[#smallcaps[comp]#text(number-type: "old-style")[2823]],',
			"      align(center)[SID: #sid],",
			'      align(right)[#text(number-type: "old-style")[#type #number]],',
			"    )",
			"    #v(-5pt)",
			"    #line(length: 100%, stroke: 0.75pt)",
			"  ],",
			'  numbering: "— 1 / 1 —",',
			")",
			"",
			"// Font setup",
			'#set text(font: "TeX Gyre Pagella", size: 13pt)',
			"",
			"// Heading settings",
			'#set heading(numbering: "1.")',
			"#show heading: it => {",
			"  set par(first-line-indent: (amount: 0pt, all: true))",
			"  v(0.25em)",
			"  it",
			"  v(0.25em)",
			"}",
			"",
			"// Paragraph indentation",
			"#set par(",
			"  justify: true,",
			"  first-line-indent: (amount: 1.5em, all: true),",
			"  spacing: 0.85em,",
			")",
			"",
			"// Part a) b) c)",
			"#let part(label, content) = pad(left: 1.5em)[",
			"  #grid(",
			"    columns: (1.5em, 1fr),",
			"    [#label], content,",
			"  )",
			"]",
			"",
			'// Solution header "Solution X."',
			"#let solution(num) = [",
			"  #set par(first-line-indent: 0pt)",
			"  *Solution #num.*",
			"]",
			"",
			'// Problem header "Problem X."',
			"#let problem(num) = [",
			"  #set par(first-line-indent: 0pt)",
			"  *Problem #num.*",
			"]",
			"",
			"// Inline math stuff for algorithms",
			"#let O(n) = $O(#n)$",
			"",
			"// Template for pseudo-code",
			"#let pseudocode(body) = block(",
			"  stroke: 0.7pt,",
			"  inset: 4pt,",
			"  radius: 2pt,",
			"  width: 100%,",
			")[",
			"  #pseudocode-list(",
			'    line-numbering: "1:",',
			"    indentation: 2em,",
			'    line-number-supplement: "",',
			"  )[#body]",
			"]",
			"",
			"",
			"// ======= DOCUMENT BODY ========",
			"",
			"",
		}),
	}),
}
